(** [Gen_key.t] is the key used to identify the targets generated by a [Scheme.t].
    Now just a [Path.Rel.t] *)

open! Core

type t [@@deriving sexp, hash, compare, bin_io]
include Hashable_binable with type t := t
include Comparable_binable with type t := t

val create : dir:Path.Rel.t -> t
val to_string : t -> string
val directory : t -> Path.Rel.t
